version: '3.3'
services:
  mariadb:
    image: mariadb:10.4.21
    ports: 
      - "127.0.0.1:3306:3306"
    volumes:
        - mariadb:/var/lib/mysql
        - ./initdb:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_ROOT_PASSWORD: ""

volumes:
  mariadb: